spring:
  application:
    name: samuel_shop
  datasource:
    url: jdbc:mariadb://10.10.100.42:3306/datmv_samuel_shop
    username: tts_vissoft
    password: Vissoft@2024
    driver-class-name:
      org.mariadb.jdbc.Driver
      # url: "jdbc:mysql://localhost:3306/vissoft"
      # username: root
      # password: 17082002
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  redis:
    # host: localhost
    # port: 6379
    host: 10.10.100.42
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  # elasticsearch:
  #   host: localhost
  #   port: 9200
  
server:
  port: 8080
  servlet:
    context-path: /api/v1

kafka:
  topics:
    create-product: create_product
    update-product: update_product
    delete-product: delete_product

jwt:
  signerKey: "HNHRxud40W4l8FH8nNCbFuMcl7bnj9bb7WUudcz6sAHVGBYHJQbajJqwmXWjbQFG"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
